### ISSUE TITLE
L2X9Core’s anti lag seems to be causing chunk loading issues

### ISSUE THREAD

**Issue by ZoomGC** [L2X9org/L2X9Core#16]
Here is part of the console’s output:
“org.l2x9.l2x9core.listeners.antilag.EntityPerChunkLimit.onSecondPass(EntityPerChunkLimit.java:21)”
Here’s the full output:
https://mcpaste.io/0aab5330a8091ee8

It seems that the antilag is causing chunks to load asynchronously, which I’m not sure how to fix or why it’s happening as the plugin was working fine beforehand, I changed the entity limits around and it must’ve had to change them all at once or something, but I’m not sure if that’d really cause that issue, thanks in advance

-ZoomGC
P.S Hey 254_nm, remember me? XD

**Comment by ghost** [comment]
This plugin is not a good plugin to use at all, the chunkloading issues are because its badly and not optimized code, stop using this plugin will fix it

**Comment by b00p1** [comment]
This plugin is no longer developed. A newer version is being made by the developer

**Comment by 254nm** [comment]
This version has been discontinued due to all of its legacy (bad) code written before i knew what i was doing. I will be posting a full rewrite shortly. This particular bug has been fixed in the rewrite
